#!/usr/bin/env python3
"""
Generate a C header file that embeds Metal kernel sources as a string literal.

Usage:
    python3 embed_metal.py <output_header> <metal_file1> [<metal_file2> ...]

The output header defines a static const char* ds4_gpu_embedded_extras containing
the concatenation of all input files, each preceded by a newline and a comment
like "// appended <path>".
"""

import sys
import os

def escape_c_string(text):
    """Escape text for a C string literal."""
    res = []
    for ch in text:
        if ch == '\\':
            res.append('\\\\')
        elif ch == '"':
            res.append('\\"')
        elif ch == '\n':
            res.append('\\n')
        elif ch == '\t':
            res.append('\\t')
        elif ord(ch) < 0x20:
            # Escape other control characters as \xHH
            res.append(f'\\x{ord(ch):02x}')
        else:
            res.append(ch)
    return ''.join(res)

def generate(output_path, input_files):
    lines = []
    lines.append('// Auto-generated by embed_metal.py. DO NOT EDIT.')
    lines.append('#ifndef DS4_GPU_EMBEDDED_EXTRAS_H')
    lines.append('#define DS4_GPU_EMBEDDED_EXTRAS_H')
    lines.append('')
    lines.append('static const char *ds4_gpu_embedded_extras =')
    
    # Build the concatenated string
    parts = []
    for fpath in input_files:
        with open(fpath, 'r', encoding='utf-8') as f:
            content = f.read()
        # Use the same format as ds4_gpu_full_source: "\n// appended <path>\n<content>\n"
        # Note: the runtime code uses loaded_path which could be the absolute path if overridden.
        # We just use the relative path as given.
        parts.append(f'\n// appended {fpath}\n{content}\n')
    
    concatenated = ''.join(parts)
    
    # Split the concatenated string into chunks to avoid overly long lines in the C file.
    # C99 allows string literal concatenation.
    chunk_size = 1000
    start = 0
    while start < len(concatenated):
        chunk = concatenated[start:start + chunk_size]
        lines.append(f'    "{escape_c_string(chunk)}"')
        start += chunk_size
    
    lines.append('    ;')
    lines.append('')
    lines.append('#endif /* DS4_GPU_EMBEDDED_EXTRAS_H */')
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    
    print(f"Generated {output_path} from {len(input_files)} input files")

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        sys.exit(1)
    output = sys.argv[1]
    inputs = sys.argv[2:]
    generate(output, inputs)
